name: Build Image & Deploy ECS (Controlled)

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # manual trigger for infra changes

env:
  IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPO }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push to ECR
        run: |
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

  terraform-deploy:
    name: Terraform ECS Infra Deploy
    runs-on: ubuntu-latest
    needs: []  # independent, triggered manually

    if: github.event_name == 'workflow_dispatch'

    defaults:
      run:
        working-directory: .github/terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" -var="ecr_repo=${{ secrets.ECR_REPO }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" -var="ecr_repo=${{ secrets.ECR_REPO }}"
